const GET_EXPERIENCES_REQUEST = "GET_PROJECTS_REQUEST";
const GET_EXPERIENCES_SUCCESS = "GET_EXPERIENCES_SUCCESS";
const GET_EXPERIENCES_ERROR = "GET_EXPERIENCES_ERROR";

const GET_EXPERIENCE_BY_NAME_REQUEST = "GET_EXPERIENCE_BY_NAME_REQUEST";
const GET_EXPERIENCE_BY_NAME_SUCCESS = "GET_EXPERIENCE_BY_NAME_SUCCESS";
const GET_EXPERIENCE_BY_NAME_ERROR = "GET_EXPERIENCE_BY_NAME_ERROR";

export {
  GET_EXPERIENCES_REQUEST,
  GET_EXPERIENCES_SUCCESS,
  GET_EXPERIENCES_ERROR,

  
  GET_EXPERIENCE_BY_NAME_REQUEST,
  GET_EXPERIENCE_BY_NAME_SUCCESS,
  GET_EXPERIENCE_BY_NAME_ERROR,
};
