const GET_EXPERIENCES_REQUEST = "GET_PROJECTS_REQUEST";
const GET_EXPERIENCES_SUCCESS = "GET_EXPERIENCES_SUCCESS";
const GET_EXPERIENCES_ERROR = "GET_EXPERIENCES_ERROR";

export {
  GET_EXPERIENCES_REQUEST,
  GET_EXPERIENCES_SUCCESS,
  GET_EXPERIENCES_ERROR,
};
