const GET_EDUCATION_REQUEST = "GET_EDUCATION_REQUEST";
const GET_EDUCATION_SUCCESS = "GET_EDUCATION_SUCCESS";
const GET_EDUCATION_ERROR = "GET_EDUCATION_ERROR";

export { GET_EDUCATION_REQUEST, GET_EDUCATION_SUCCESS, GET_EDUCATION_ERROR };
