const GET_SKILLS_REQUEST = "GET_SKILLS_REQUEST";
const GET_SKILLS_SUCCESS = "GET_SKILLS_SUCCESS";
const GET_SKILLS_ERROR = "GET_SKILLS_ERROR";

const GET_SKILL_BY_SLUG_REQUEST = "GET_SKILL_BY_SLUG_REQUEST";
const GET_SKILL_BY_SLUG_SUCCESS = "GET_SKILL_BY_SLUG_SUCCESS";
const GET_SKILL_BY_SLUG_ERROR = "GET_SKILL_BY_SLUG_ERROR";


export {
  GET_SKILLS_REQUEST,
  GET_SKILLS_SUCCESS,
  GET_SKILLS_ERROR,


  GET_SKILL_BY_SLUG_REQUEST,
  GET_SKILL_BY_SLUG_SUCCESS,
  GET_SKILL_BY_SLUG_ERROR,
};
